#!/bin/bash

base=`pwd`
function runtest
{
	cd $base/$1
	list=`echo *test.php`
	for file in $list
	do
		echo ""
		echo "Running test $file"
		phpunit $file
	done
}


runtest "sys/app"
runtest "sys/utility"
